- name: ensure packages are installed
  apt:
    name:
      - dehydrated
      - ruby-faraday
    state: present
    default_release: buster-backports
  environment:
    DEBIAN_FRONTEND: noninteractive
