- name: run debian specific acme tasks
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: add the primary name to the domains.txt file
  lineinfile:
    path: /etc/dehydrated/domains.txt
    create: yes
    line: "{{ subject_name }}"
    insertbefore: BOF

- name: add SAN entries to the domains.txt file
  lineinfile:
    path: /etc/dehydrated/domains.txt
    line: "{{ item }}"
    insertafter: '^{{ subject_name }}$'
  with_items: "{{ alternate_names | default([], true) }}"
