- name: run debian specific acme tasks
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: generate dehydrated domains.txt file
  copy:
    content: "{{ subject_name }}\n"
    dest: /etc/dehydrated/domains.txt

- name: add SAN entries to the domains.txt file
  lineinfile:
    path: /etc/dehydrated/domains.txt
    line: "{{ item }}"
    insertafter: '^{{ subject_name }}$'
  with_items: "{{ alternate_names | default([], true) }}"
