- name: update installed packages
  apt:
    upgrade: dist
    update_cache: yes

- name: enable buster-backports
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present

- name: install git from buster-backports
  apt:
    name: git
    default_release: buster-backports
    state: present

- name: ensure necessary packages are installed
  apt:
    name: "{{ debian_packages }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: ensure apparmor utilities are installed
  apt:
    name:
      - apparmor
      - apparmor-utils
      - auditd
      - apparmor-profiles
      - apparmor-profiles-extra
    state: present

- name: ensure auditd starts on bootup
  service:
    name: auditd
    state: started
    enabled: yes

- name: set the executable bit on rrsync
  file:
    path: /usr/share/doc/rsync/scripts/rrsync
    mode: "0555"

- name: make sure rrsync is found in the PATH
  file:
    src: /usr/share/doc/rsync/scripts/rrsync
    dest: /usr/bin/rrsync
    state: link
